Repository sustainable-computing-io/kepler-operator, pull requests merged in 2025-09, with the labels that each got.

#600 feat(secrets): allow additional secrets to be mounted to kepler
  api/v1alpha1/power_monitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitors.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitors.yaml
  config/samples/kepler.system_v1alpha1_powermonitor.yaml
  docs/api.md
  internal/controller/power_monitor_internal.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/reconciler/power-monitor.go
  pkg/reconciler/power-monitor_test.go
  tests/e2e/power_monitor_internal_secrets_test.go
  tests/e2e/power_monitor_test.go
  tests/run-e2e.sh
  tests/utils/assertions.go
  tests/utils/framework.go
  tests/utils/power_monitor_internal_builder.go
Labels: feat, ci

#603 chore: bump up Kepler to v0.11.0
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/config/config.go
  internal/config/config_test.go
  internal/config/redfish/config.go
  internal/config/redfish/config_test.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  tests/e2e/main_test.go
Labels: chore

#606 fix(powermonitor): remove All option from namespace and pod dropdowns
  pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json
Labels: fix
