Repository sustainable-computing-io/kepler-operator, pull requests merged in 2025-10, with the labels that each got.

#607 chore(kepler): bump up version to 0.11.2
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  tests/e2e/main_test.go
Labels: chore

#588 feat: add secret expiration reconciler
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  cmd/main.go
  config/manager/overlays/openshift/kustomization.yaml
  config/manifests/bases/kepler-operator.clusterserviceversion.yaml
  internal/controller/config.go
  internal/controller/power_monitor_internal.go
  internal/controller/token_expiry.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/reconciler/power-monitor.go
  pkg/reconciler/security.go
  pkg/reconciler/security_test.go
  pkg/reconciler/service_monitor.go
  pkg/reconciler/service_monitor_test.go
Labels: manual-validation, feat

#611 docs: improve must-gather guide
  must-gather/README.md
Labels: docs

#601 chore: switch from v1alpha1 to main
  .github/workflows/pr-checks.yaml
  .github/workflows/push.yaml
  README.md
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  config/manifests/bases/kepler-operator.clusterserviceversion.yaml
Labels: chore

#617 chore: remove helm release artifact
  helm-releases/kepler-operator-helm-0.22.2.tgz
Labels: chore

#618 docs: update v1alpha1 reference to main
  README.md
  manifests/helm/kepler-operator/Chart.yaml
  must-gather/README.md
Labels: docs
