Repository sustainable-computing-io/kepler-operator, pull requests merged in 2025-05, with the labels that each got.

#482 chore: bump up kepler reboot
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/config/config.go
  internal/config/config_rapl_test.go
  internal/config/config_test.go
  internal/controller/config.go
Labels: manual-validation

#488 ci: add dedicated go vet job to pr checks
  .github/workflows/pr-checks.yaml
  Makefile
Labels: ci

#487 ci: update release workflow
  .github/release.yml
  .github/workflows/pr-checks.yaml
  .github/workflows/publish-images.yaml
  .github/workflows/release.yaml
Labels: ci

#492 ci: ensure go vet job also runs on file change
  .github/workflows/pr-checks.yaml
Labels: ci

#491 test: update e2e script to accept commands
  .github/workflows/pr-checks.yaml
  tests/run-e2e.sh
Labels: test

#493 ci: add job for labeling PR
  .github/workflows/assign-labels.yaml
Labels: ci

#480 feat(dashboards): Add Power Monitor Info/Node OCP Dashboards
  internal/controller/power_monitor_internal.go
  pkg/components/power-monitor/assets/dashboards/power-monitor-node-info.json
  pkg/components/power-monitor/assets/dashboards/power-monitor-per-node.json
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
Labels: manual-validation, feat

#496 ci: make sure golang based jobs depend on the check-changes job
  .github/workflows/pr-checks.yaml
Labels: ci

#477 chore: update must-gather to support power-monitor
  must-gather/gather
Labels: manual-validation, chore

#499 fix: ensure that power-monitor status is shown on console
  api/v1alpha1/power_monitor_internal_types.go
  api/v1alpha1/power_monitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitors.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitors.yaml
  docs/api.md
  internal/controller/power_monitor.go
  internal/controller/power_monitor_internal.go
  pkg/utils/test/assertions.go
  pkg/utils/test/framework.go
  tests/e2e/power_monitor_test.go
Labels: fix

#503 chore: bump up supported ocp version for the operator
  bundle/metadata/annotations.yaml
  hack/bundle.sh
Labels: chore

#498 Fix yaml error during the script run on "./hack/dashboard/openshift/deploy-grafana.sh"
  hack/dashboard/openshift/grafana-config/01-grafana-instance.yaml
  hack/dashboard/openshift/grafana-config/03-grafana-datasource-UPDATETHIS.yaml
Labels: manual-validation

#507 chore(dashboard): update cpu info panel to show total number of cores
  pkg/components/power-monitor/assets/dashboards/power-monitor-node-info.json
Labels: chore

#504 docs: add relevant status in the README
  README.md
Labels: docs

#506 docs: add release workflow
  docs/design/assets/release.png
  docs/design/assets/release.uml
  docs/design/release.md
Labels: docs

#509 tests(power-monitor): replace enable_vm_test env variable with command-line flag
  tests/e2e/main_test.go
  tests/e2e/power_monitor_internal_test.go
  tests/e2e/power_monitor_test.go
  tests/run-e2e.sh
Labels: test

#511 test: use latest kepler release
  tests/e2e/main_test.go
Labels: test

#519 chore: ensure that required precommit hooks are installed
  .pre-commit-config.yaml
Labels: chore

#520 chore: rename kepler config file
  pkg/components/power-monitor/deployment.go
Labels: chore

#521 chore: bump up kepler reboot
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/config/config.go
  internal/config/config_test.go
  internal/controller/config.go
  tests/e2e/main_test.go
Labels: chore

#510 feat: add support for custom config maps
  api/v1alpha1/power_monitor_internal_types.go
  api/v1alpha1/power_monitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_powermonitors.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitorinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_powermonitors.yaml
  docs/api.md
  go.mod
  internal/config/config.go
  internal/config/config_test.go
  internal/controller/power_monitor.go
  internal/controller/power_monitor_internal.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/reconciler/power-monitor.go
  pkg/reconciler/updater.go
  pkg/utils/test/framework.go
  tests/e2e/power_monitor_test.go
Labels: feat
