Repository sustainable-computing-io/kepler-operator, pull requests merged in 2025-07, with the labels that each got.

#553 chore: use log level as info for Kepler
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  config/samples/kepler.system_v1alpha1_powermonitor.yaml
Labels: chore

#552 chore: remove older Kepler related steps in must-gather
  must-gather/gather
  must-gather/utils
Labels: manual-validation, chore

#564 chore: rename MountSecretAnnotationToDaemonset and MountConfigMapToDaemonSet
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/reconciler/power-monitor.go
  pkg/reconciler/security.go
Labels: chore

#565 chore: change timeout depending on cluster type
  internal/controller/power_monitor_internal.go
  pkg/reconciler/security.go
Labels: manual-validation, chore

#567 chore: add example for security setting in PowerMonitor CR
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  config/samples/kepler.system_v1alpha1_powermonitor.yaml
  tests/run-e2e.sh
Labels: chore

#570 chore: add error propagation to deployment.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/reconciler/power-monitor.go
  pkg/reconciler/security.go
Labels: chore

#573 ci: ignore utils from codecov generation
  codecov.yml
Labels: ci

#572 test: ensure RBAC e2e can run on OpenShift
  pkg/utils/test/framework.go
  tests/e2e/main_test.go
  tests/e2e/power_monitor_internal_test.go
  tests/e2e/power_monitor_test.go
Labels: test

#576 chore: move utils outside e2e
  codecov.yml
  go.mod
  go.sum
  pkg/reconciler/deleter_test.go
  tests/Dockerfile
  tests/e2e/kepler_internal_test.go
  tests/e2e/kepler_test.go
  tests/e2e/oc_get_test.go
  tests/e2e/oc_literal_test.go
  tests/e2e/power_monitor_internal_test.go
  tests/e2e/power_monitor_test.go
  tests/go.mod
  tests/go.sum
  tests/run-e2e.sh
  tests/utils/assertions.go
  tests/utils/framework.go
  tests/utils/kepler_internal_builder.go
  tests/utils/oc/adm_top.go
  tests/utils/oc/command.go
  tests/utils/oc/doc.go
  tests/utils/oc/exec.go
  tests/utils/oc/exec_test.go
  tests/utils/oc/get.go
  tests/utils/oc/get_test.go
  tests/utils/oc/literal.go
  tests/utils/oc/literal_test.go
  tests/utils/oc/logs.go
  tests/utils/oc/runner.go
  tests/utils/power_monitor_internal_builder.go
Labels: chore

#580 chore: track Makefile as part of check changes
  .github/publish-images/action.yaml
  .github/tools-cache/action.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/push.yaml
  .github/workflows/release.yaml
  Makefile
Labels: chore

#585 test: set the deployment-namespace to PowerMonitor ns
  tests/e2e/main_test.go
Labels: test

#584 chore: set OCP version range from OCP 4.17-4.19
  bundle/metadata/annotations.yaml
  hack/bundle.sh
Labels: chore

#586 test: wait for reconciliation before creating resources
  tests/e2e/power_monitor_internal_test.go
  tests/e2e/power_monitor_test.go
  tests/utils/framework.go
Labels: test

#587 test: wait for availability as false before enabling fake cpu meter
  tests/utils/framework.go
Labels: test

#590 chore: remove deprecated Kepler CR
  .github/workflows/pr-checks.yaml
  api/v1alpha1/kepler_internal_types.go
  api/v1alpha1/kepler_types.go
  api/v1alpha1/kepler_webhook.go
  api/v1alpha1/power_monitor_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplerinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml
  cmd/main.go
  config/crd/bases/kepler.system.sustainable.computing.io_keplerinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml
  config/crd/kustomization.yaml
  config/crd/patches/cainjection_in_keplers.yaml
  config/crd/patches/webhook_in_keplers.yaml
  config/manifests/bases/kepler-operator.clusterserviceversion.yaml
  config/samples/kepler.system_v1alpha1_kepler.yaml
  config/samples/kustomization.yaml
  config/webhook/manifests.yaml
  docs/api.md
  internal/controller/kepler.go
  internal/controller/kepler_internal.go
  internal/controller/power_monitor.go
  pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json
  pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
  pkg/components/exporter/exporter.go
  pkg/components/exporter/exporter_test.go
  pkg/reconciler/kepler.go
  tests/e2e/kepler_internal_test.go
  tests/e2e/kepler_test.go
  tests/e2e/main_test.go
  tests/run-e2e.sh
  tests/utils/assertions.go
  tests/utils/framework.go
  tests/utils/kepler_internal_builder.go
Labels: chore
