Repository sustainable-computing-io/kepler-operator, pull requests merged in 2025-06, with the labels that each got.

#526 ci: split test and codecov upload execution
  .github/codecov-upload/action.yaml
  .github/workflows/pr-checks.yaml
  .github/workflows/publish-images.yaml
  .github/workflows/test-and-codecov.yaml
Labels: ci

#525 chore: bump up kepler reboot
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/config/builder.go
  internal/config/config.go
  internal/config/config_test.go
  internal/controller/config.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  tests/e2e/main_test.go
Labels: chore

#531 chore: remove service monitor interval from powermonitor
  pkg/components/power-monitor/deployment.go
Labels: chore

#528 ci: specify codecov secret to the workflow
  .github/workflows/pr-checks.yaml
  .github/workflows/push.yaml
  .github/workflows/test-and-codecov.yaml
Labels: ci

#534 chore: add Kepler CR deprecation notice to dashboards
  pkg/components/exporter/assets/dashboards/power-monitoring-by-ns.json
  pkg/components/exporter/assets/dashboards/power-monitoring-overview.json
Labels: chore

#533 ci: ensure only powermonitor tests are executed
  .github/workflows/pr-checks.yaml
  tests/e2e/kepler_internal_test.go
  tests/e2e/kepler_test.go
  tests/e2e/main_test.go
Labels: ci

#530 feat(pod): Operator support Pod power
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/config/config.go
  internal/config/config_test.go
  internal/controller/config.go
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  tests/e2e/main_test.go
Labels: feat

#536 chore: enhance OpenShift dashboards
  internal/controller/power_monitor_internal.go
  pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json
  pkg/components/power-monitor/assets/dashboards/power-monitor-node-info.json
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
Labels: chore

#532 test: update the e2e to use config maps for VM test setup
  .github/workflows/pr-checks.yaml
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
  pkg/utils/test/framework.go
  pkg/utils/test/power_monitor_internal_builder.go
  tests/e2e/main_test.go
  tests/e2e/power_monitor_internal_test.go
  tests/e2e/power_monitor_test.go
  tests/run-e2e.sh
Labels: test

#537 chore: update total power consumption panels to filter by zone
  pkg/components/power-monitor/assets/dashboards/power-monitor-namespace-info.json
  pkg/components/power-monitor/assets/dashboards/power-monitor-overview.json
  pkg/components/power-monitor/deployment.go
  pkg/components/power-monitor/deployment_test.go
Labels: chore

#538 chore(dashboard): use table to show current power consumption
  pkg/components/power-monitor/assets/dashboards/power-monitor-overview.json
Labels: chore

#541 chore: use build-manager target for building operator
  Dockerfile
  Makefile
Labels: chore

#535 chore: make kepler CR deprecated
  api/v1alpha1/kepler_internal_types.go
  api/v1alpha1/kepler_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplerinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_keplerinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml
  config/manifests/bases/kepler-operator.clusterserviceversion.yaml
  docs/api.md
  internal/controller/kepler.go
  internal/controller/kepler_internal.go
Labels: chore

#543 chore: allow CGO_ENABLED to be set during manager build
  Makefile
Labels: chore

#544 chore: bump up Kepler version
  Makefile
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  internal/controller/config.go
  tests/e2e/main_test.go
Labels: chore

#548 chore: add deprecation notice to Kepler CR description
  api/v1alpha1/kepler_internal_types.go
  api/v1alpha1/kepler_types.go
  bundle/manifests/kepler-operator.clusterserviceversion.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplerinternals.yaml
  bundle/manifests/kepler.system.sustainable.computing.io_keplers.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_keplerinternals.yaml
  config/crd/bases/kepler.system.sustainable.computing.io_keplers.yaml
  config/manifests/bases/kepler-operator.clusterserviceversion.yaml
  docs/api.md
Labels: chore

#547 ci: use custom hook for linting PR commits
  .github/workflows/pr-checks.yaml
  .pre-commit-config.yaml
Labels: ci

#549 test: validate PowerMonitor CR and Kepler image in upgrade test
  tests/run-e2e.sh
Labels: test
